CREATE DATABASE IF NOT EXISTS vehicle_db;
USE vehicle_db;

CREATE TABLE IF NOT EXISTS vehicle (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL,
    license_plate VARCHAR(50) NOT NULL
);
